/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aparelhos;

/**
 *
 * @author Fabricio
 */
public class Aparelhos extends javax.swing.JFrame {

    /**
     * Creates new form Aparelhos
     */
    public Aparelhos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIDaparelho = new javax.swing.JLabel();
        jtidaparelho = new javax.swing.JTextField();
        jlModelo = new javax.swing.JLabel();
        jtmodelo = new javax.swing.JTextField();
        jlimei = new javax.swing.JLabel();
        jtIMEI = new javax.swing.JTextField();
        jbsalvar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aparelhos");
        getContentPane().setLayout(null);

        jlIDaparelho.setText("ID Aparelho");
        getContentPane().add(jlIDaparelho);
        jlIDaparelho.setBounds(40, 10, 80, 14);
        getContentPane().add(jtidaparelho);
        jtidaparelho.setBounds(40, 30, 81, 30);

        jlModelo.setText("Modelo");
        getContentPane().add(jlModelo);
        jlModelo.setBounds(40, 70, 90, 14);

        jtmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtmodeloActionPerformed(evt);
            }
        });
        getContentPane().add(jtmodelo);
        jtmodelo.setBounds(40, 90, 350, 30);

        jlimei.setText("IMEI");
        getContentPane().add(jlimei);
        jlimei.setBounds(40, 140, 130, 14);
        getContentPane().add(jtIMEI);
        jtIMEI.setBounds(40, 160, 350, 30);

        jbsalvar.setText("Salvar");
        jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jbsalvar);
        jbsalvar.setBounds(170, 230, 100, 40);

        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbcancelar);
        jbcancelar.setBounds(290, 230, 100, 40);

        setBounds(0, 0, 800, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void jtmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtmodeloActionPerformed

        

        // TODO add your handling code here:
    }//GEN-LAST:event_jtmodeloActionPerformed

    private void jbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalvarActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jbsalvarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aparelhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aparelhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aparelhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aparelhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aparelhos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbsalvar;
    private javax.swing.JLabel jlIDaparelho;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlimei;
    private javax.swing.JTextField jtIMEI;
    private javax.swing.JTextField jtidaparelho;
    private javax.swing.JTextField jtmodelo;
    // End of variables declaration//GEN-END:variables
}
