/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clientes;

/**
 *
 * @author Fabricio
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlID = new javax.swing.JLabel();
        jtid = new javax.swing.JTextField();
        jrPF = new javax.swing.JRadioButton();
        jrPJ = new javax.swing.JRadioButton();
        jlNome = new javax.swing.JLabel();
        jtnome = new javax.swing.JTextField();
        jlCPF = new javax.swing.JLabel();
        jtCPF = new javax.swing.JTextField();
        jlCNPJ = new javax.swing.JLabel();
        jtCNPJ = new javax.swing.JTextField();
        jllogradouro = new javax.swing.JLabel();
        jtlogradouro = new javax.swing.JTextField();
        jlnúmero = new javax.swing.JLabel();
        jtnúmero = new javax.swing.JTextField();
        jlcomplemento = new javax.swing.JLabel();
        jtcomplemento = new javax.swing.JTextField();
        jlbairro = new javax.swing.JLabel();
        jtbairro = new javax.swing.JTextField();
        jlcidade = new javax.swing.JLabel();
        jtcidade = new javax.swing.JTextField();
        jlcep = new javax.swing.JLabel();
        jtCEP = new javax.swing.JTextField();
        jlUF = new javax.swing.JLabel();
        jtUF = new javax.swing.JTextField();
        jltelefone1 = new javax.swing.JLabel();
        jttelefone1 = new javax.swing.JTextField();
        jltelefone2 = new javax.swing.JLabel();
        jttelefone2 = new javax.swing.JTextField();
        jlemail = new javax.swing.JLabel();
        jtemail = new javax.swing.JTextField();
        jbsalvar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de clientes");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(800, 400, 800, 400));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 800, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setSize(new java.awt.Dimension(1200, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jlID.setText("ID Cliente");
        getContentPane().add(jlID);
        jlID.setBounds(40, 10, 80, 14);
        getContentPane().add(jtid);
        jtid.setBounds(40, 30, 81, 30);

        jrPF.setText("PF");
        getContentPane().add(jrPF);
        jrPF.setBounds(180, 30, 40, 23);

        jrPJ.setText("PJ");
        getContentPane().add(jrPJ);
        jrPJ.setBounds(240, 30, 40, 23);

        jlNome.setText("Nome");
        getContentPane().add(jlNome);
        jlNome.setBounds(40, 60, 90, 14);

        jtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtnome);
        jtnome.setBounds(40, 80, 350, 30);

        jlCPF.setText("CPF");
        getContentPane().add(jlCPF);
        jlCPF.setBounds(400, 60, 80, 14);
        getContentPane().add(jtCPF);
        jtCPF.setBounds(400, 80, 120, 30);

        jlCNPJ.setText("CNPJ");
        getContentPane().add(jlCNPJ);
        jlCNPJ.setBounds(530, 60, 100, 14);
        getContentPane().add(jtCNPJ);
        jtCNPJ.setBounds(530, 80, 160, 30);

        jllogradouro.setText("Logradouro");
        getContentPane().add(jllogradouro);
        jllogradouro.setBounds(40, 110, 140, 14);
        getContentPane().add(jtlogradouro);
        jtlogradouro.setBounds(40, 130, 350, 30);

        jlnúmero.setText("Número");
        getContentPane().add(jlnúmero);
        jlnúmero.setBounds(400, 110, 60, 14);
        getContentPane().add(jtnúmero);
        jtnúmero.setBounds(400, 130, 60, 30);

        jlcomplemento.setText("Complemento");
        getContentPane().add(jlcomplemento);
        jlcomplemento.setBounds(470, 110, 170, 14);
        getContentPane().add(jtcomplemento);
        jtcomplemento.setBounds(470, 130, 220, 30);

        jlbairro.setText("Bairro");
        getContentPane().add(jlbairro);
        jlbairro.setBounds(40, 160, 150, 14);
        getContentPane().add(jtbairro);
        jtbairro.setBounds(40, 180, 210, 30);

        jlcidade.setText("Cidade");
        getContentPane().add(jlcidade);
        jlcidade.setBounds(260, 160, 150, 14);
        getContentPane().add(jtcidade);
        jtcidade.setBounds(260, 180, 260, 30);

        jlcep.setText("CEP");
        getContentPane().add(jlcep);
        jlcep.setBounds(530, 160, 100, 14);
        getContentPane().add(jtCEP);
        jtCEP.setBounds(530, 180, 110, 30);

        jlUF.setText("UF");
        getContentPane().add(jlUF);
        jlUF.setBounds(650, 160, 40, 14);
        getContentPane().add(jtUF);
        jtUF.setBounds(649, 180, 40, 30);

        jltelefone1.setText("Telefone 1");
        getContentPane().add(jltelefone1);
        jltelefone1.setBounds(40, 210, 130, 14);
        getContentPane().add(jttelefone1);
        jttelefone1.setBounds(40, 230, 160, 30);

        jltelefone2.setText("Telefone 2");
        getContentPane().add(jltelefone2);
        jltelefone2.setBounds(210, 210, 150, 14);
        getContentPane().add(jttelefone2);
        jttelefone2.setBounds(210, 230, 160, 30);

        jlemail.setText("E-mail");
        getContentPane().add(jlemail);
        jlemail.setBounds(380, 210, 210, 14);
        getContentPane().add(jtemail);
        jtemail.setBounds(380, 230, 310, 30);

        jbsalvar.setText("Salvar");
        jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jbsalvar);
        jbsalvar.setBounds(470, 290, 100, 40);

        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbcancelar);
        jbcancelar.setBounds(590, 290, 100, 40);

        setSize(new java.awt.Dimension(737, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        
        

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalvarActionPerformed



        
// TODO add your handling code here:
    }//GEN-LAST:event_jbsalvarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

System.exit(0);


// TODO add your handling code here:
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnomeActionPerformed




 // TODO add your handling code here:
    }//GEN-LAST:event_jtnomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbsalvar;
    private javax.swing.JLabel jlCNPJ;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlUF;
    private javax.swing.JLabel jlbairro;
    private javax.swing.JLabel jlcep;
    private javax.swing.JLabel jlcidade;
    private javax.swing.JLabel jlcomplemento;
    private javax.swing.JLabel jlemail;
    private javax.swing.JLabel jllogradouro;
    private javax.swing.JLabel jlnúmero;
    private javax.swing.JLabel jltelefone1;
    private javax.swing.JLabel jltelefone2;
    private javax.swing.JRadioButton jrPF;
    private javax.swing.JRadioButton jrPJ;
    private javax.swing.JTextField jtCEP;
    private javax.swing.JTextField jtCNPJ;
    private javax.swing.JTextField jtCPF;
    private javax.swing.JTextField jtUF;
    private javax.swing.JTextField jtbairro;
    private javax.swing.JTextField jtcidade;
    private javax.swing.JTextField jtcomplemento;
    private javax.swing.JTextField jtemail;
    private javax.swing.JTextField jtid;
    private javax.swing.JTextField jtlogradouro;
    private javax.swing.JTextField jtnome;
    private javax.swing.JTextField jtnúmero;
    private javax.swing.JTextField jttelefone1;
    private javax.swing.JTextField jttelefone2;
    // End of variables declaration//GEN-END:variables
}
