/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Técnicos;

/**
 *
 * @author Fabricio
 */
public class Técnicos extends javax.swing.JFrame {

    /**
     * Creates new form Técnicos
     */
    public Técnicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIDtecnico = new javax.swing.JLabel();
        jtidtecnico = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jtnometecnico = new javax.swing.JTextField();
        jltelefone = new javax.swing.JLabel();
        jttelefonetecnico = new javax.swing.JTextField();
        jlemail = new javax.swing.JLabel();
        jtemailtecnico = new javax.swing.JTextField();
        jbsalvar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Técnicos");
        getContentPane().setLayout(null);

        jlIDtecnico.setText("ID Técnico");
        getContentPane().add(jlIDtecnico);
        jlIDtecnico.setBounds(40, 10, 80, 14);
        getContentPane().add(jtidtecnico);
        jtidtecnico.setBounds(40, 30, 81, 30);

        jlNome.setText(" Nome Técnico");
        getContentPane().add(jlNome);
        jlNome.setBounds(40, 70, 90, 14);

        jtnometecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnometecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(jtnometecnico);
        jtnometecnico.setBounds(40, 90, 350, 30);

        jltelefone.setText("Telefone Técnico");
        getContentPane().add(jltelefone);
        jltelefone.setBounds(40, 140, 130, 14);
        getContentPane().add(jttelefonetecnico);
        jttelefonetecnico.setBounds(40, 160, 350, 30);

        jlemail.setText(" E-mail Técnico");
        getContentPane().add(jlemail);
        jlemail.setBounds(40, 200, 210, 14);
        getContentPane().add(jtemailtecnico);
        jtemailtecnico.setBounds(40, 220, 350, 30);

        jbsalvar.setText("Salvar");
        jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jbsalvar);
        jbsalvar.setBounds(170, 280, 100, 40);

        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbcancelar);
        jbcancelar.setBounds(290, 280, 100, 40);

        setBounds(0, 0, 800, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void jtnometecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnometecnicoActionPerformed

       

        // TODO add your handling code here:
    }//GEN-LAST:event_jtnometecnicoActionPerformed

    private void jbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalvarActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jbsalvarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Técnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Técnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Técnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Técnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Técnicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbsalvar;
    private javax.swing.JLabel jlIDtecnico;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlemail;
    private javax.swing.JLabel jltelefone;
    private javax.swing.JTextField jtemailtecnico;
    private javax.swing.JTextField jtidtecnico;
    private javax.swing.JTextField jtnometecnico;
    private javax.swing.JTextField jttelefonetecnico;
    // End of variables declaration//GEN-END:variables
}
